#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Math 768 
tagline: Formalization of mathematics 
honors: false
description: Using Lean to prove things. 
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://768.s23.matthewrobertballard.com' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
# logo: '/assets/images/beta.png'

# pdf2svg: '/opt/homebrew/bin/pdf2svg' 
# destination: '../UofSC-Spring-2022-Math-300-H01.github.io'

term: Spring
year: 2023
meeting_time: Mondays, Wednesdays, and Fridays 8:30-9:45 AM
meeting_location: TBD
office : LeConte College Room 341
office_hours: TBD
bulletin_desc: Course content varies and will be announced in the schedule of classes by title. All non-degree students should request permission to register from the Graduate Director in the Mathematics Department.
prereqs: None

textbook: Theorem Proving in Lean.  

teams_url: 
github_org: 
github_classroom: 

# google_analytics: 

# Theme settings
# remote_theme: pmarsceill/just-the-docs@v0.3.3
# theme: "just-the-docs"
color_scheme: usc
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Matthew Ballard:
    - 'https://www.matthewrobertballard.com'
  Microsoft Teams:
    - ''
footer_content: '<a href="https://300.f22.matthewrobertballard.com/about_this_webpage/">About this webpage.</a> Copyright &copy; 2022 Matthew Ballard. Distributed with an <a href="https://github.com/UofSC-Fall-2022-Math-300-H01.github.io/tree/master/LICENSE.txt\">MIT license.</a> '

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  homework:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: homework
    values:
      layout: page 
  # - scope:
  #     path: ''
  #     type: worksheets
  #   values:
  #     layout: page

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

kramdown:
  math_engine: nil
#  parse_block_html: true

plugins:
  - jekyll-seo-tag
#  - jekyll-katex
